apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: ap-northeast-1
  version: '1.22'

availabilityZones: ['ap-northeast-1a', 'ap-northeast-1c', 'ap-northeast-1d']

vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  publicAccessCIDRs: ['160.237.141.236/32']

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: appmesh-controller
        namespace: appmesh-system
        labels: { aws-usage: 'application' }
      attachPolicyARNs:
        - 'arn:aws:iam::aws:policy/AWSAppMeshFullAccess'

managedNodeGroups:
  - name: bottlerocket
    instanceType: c5.large
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    amiFamily: Bottlerocket
    privateNetworking: true
    tags:
      nodegroup-type: Bottlerocket
    ssh:
      enableSsm: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        awsLoadBalancerController: true
        albIngress: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ['all']
    logRetentionInDays: 7
