apiVersion: v1
kind: Pod
metadata:
  name: oom-triger
  namespace: default
spec:
  containers:
  - name: oom-triger
    image: polinux/stress:1.0.4
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "300M", "--vm-hang", "1"]