apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
replicas:
- count: 3
  name: deployment
images:
- name: 528163014577.dkr.ecr.ap-northeast-1.amazonaws.com/sample-app
  newTag: f41d1363ecd6faf5bcf7fba120e79727ffe14a87
