apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
replicas:
- count: 5
  name: deployment
images:
- name: 528163014577.dkr.ecr.ap-northeast-1.amazonaws.com/sample-app
  newTag: 842af82b9077c9d6572a0ecfc779a2c295ace4c0
