apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: default
type: Opaque
data:
  username: YWRtaW4=
  password: MTIzNDU2NzgK
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-file-pod
spec:
  containers:
    - name: redis
      image: redis:7.0.4
      volumeMounts:
        # 参照(読み取り専用でマウント)
        - name: secret
          mountPath: '/etc/secret'
          readOnly: true
  volumes:
    # 定義
    - name: secret
      secret:
        secretName: test-secret
