apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: redis
      image: redis:7.0.4
      env:
        # コンテナ内で使用する変数名にアサイン
        - name: SECRET_USERNAME
          valueFrom:
            # Secretを参照
            secretKeyRef:
              name: test-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: password
  restartPolicy: Never
