---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: matsutanishoutarou-karpenter-demo
  region: ap-northeast-1
  version: "1.21"
managedNodeGroups:
  - instanceType: m5.large
    amiFamily: AmazonLinux2
    name: matsutanishoutarou-karpenter-demo-ng
    desiredCapacity: 1
    minSize: 1
    maxSize: 10
iam:
  withOIDC: true
