apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: pod-reader
rules:
- apiGroups: [""] # "" はコアのAPIGroupを示します
  resources: ["pods"]
  verbs: ["get", "watch", "list"]