node {
    def app

    stage('Clone repository') {
      

        checkout scm
    }

    stage('Update GIT') {
            script {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                        sh "git config user.email matsuya@h01.itscom.net"
                        sh "git config user.name ShotaroMatsuya"
                        //sh "git switch master"
                        sh "cat ./GitOps_Demo/kubernetesmanifest/deployment.yaml"
                        sh "sed -i 's+shotaromatsuya/test.*+shotaromatsuya/test:${DOCKERTAG}+g' ./GitOps_Demo/kubernetesmanifest/deployment.yaml"
                        sh "cat ./GitOps_Demo/kubernetesmanifest/deployment.yaml"
                        sh "git add ."
                        sh "git commit -m 'Done by Jenkins Job changemanifest: ${env.BUILD_NUMBER}'"
                        sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/learning-eks.git HEAD:master"
      }
    }
  }
}
}
